name: "Publish to Sigrid"
on:
  push:
    branches:
      - 'main'
jobs:
  sigridci:
    name: 'Sigrid CI'
    runs-on: ubuntu-latest
    steps:
    - name: Sigrid CI
      uses: Software-Improvement-Group/sigridci@v1.1.0
      with:
        customer: "sig"
        system: "mendix-security"
        targetquality: "3.5"
        publish: true
      env:
        SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
